language:
    node_js

node_js:
    0.10

before_install:
    npm install -g grunt-cli

install:
    npm install

script:
    grunt build:travis

env:
  global:
    - secure: BX2mSg5d3WwPOkmmKfue+5HHWq8Hp72fhMIosDTc0Z5oUbyp67Rdo/TeyInGycTaQzIIMtuu99PfMzjgdN51XgaQKkX+3obW1xH02KfUbppfttbUzwBm4SKzyoaIB1xBZxUnDfRWi11U/Ocax0CofAVd+8S50hJgxPSswxdLuzE=
    - secure: fl2qP4TKnqWb/pAgYPg7b3rMYyEJc3rnukosCzQ6Tzy0SDsxc+8OUY2k1FIk0JHYMVSYFBTOe1vNg6XVg1OAb4yAmDpIMBvtdj+fPQVlaE34BTtFgc3hgGmI1Re3bHzcsRUiI4ucIyDHIstCe9HAqvhBMIwaODJ5J9BfVy19ZNk=

addons:
    sauce_connect: true
